[theme]
  base = "light"
    primaryColor = "#3e6d8e"
    backgroundColor = "#f7f5f1"
    secondaryBackgroundColor = "#ffffff"
    textColor = "#20262b"

    [browser]
    gatherUsageStats = false
    
